# Create CSV Files

In [1]:
import pandas as pd

In [2]:
# Define the Data

weather_data = {
    'day': ['1/1/2017', '2/1/2017', '3/1/2017', '4/1/2017', '1/1/2017'],
    'temperature':[32, 35, 28, 32, 31],
    'windspeed': [6, 7, 2, 7, 4],
    'event': ['Rain', 'Sunny', 'Snow', 'Rain', 'Sunny']
}

print(weather_data, type(weather_data))

{'day': ['1/1/2017', '2/1/2017', '3/1/2017', '4/1/2017', '1/1/2017'], 'temperature': [32, 35, 28, 32, 31], 'windspeed': [6, 7, 2, 7, 4], 'event': ['Rain', 'Sunny', 'Snow', 'Rain', 'Sunny']} <class 'dict'>

In [3]:
# Create DataFrame

df = pd.DataFrame(weather_data)

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2017           35          7  Sunny
2  3/1/2017           28          2   Snow
3  4/1/2017           32          7   Rain
4  1/1/2017           31          4  Sunny

In [4]:
# DataFrame Values to CSV Values

fileName = 'weather_data.csv'

df.to_csv(fileName, index=False)

print(fileName, ' File Created Successfully!...')

weather_data.csv  File Created Successfully!...

# Create Microsoft Excel File

In [6]:
# Create Python Variables

df_stocks = pd.DataFrame({
    'tickers': ['GOOGL', 'WMT', 'MSFT'],
    'price': [845, 65, 64], 
    'pe': [30.37, 14.26, 30.97],
    'eps': [27.82, 4.61, 2.12]
})

weather_data = pd.DataFrame({
    'day': ['1/1/2017', '2/1/2017', '3/1/2017', '4/1/2017', '1/1/2017'],
    'temperature':[32, 35, 28, 32, 31],
    'windspeed': [6, 7, 2, 7, 4],
    'event': ['Rain', 'Sunny', 'Snow', 'Rain', 'Sunny']
})


print(df_stocks)

print('----------------------------------------------------------------')

print(weather_data)

  tickers  price     pe    eps
0   GOOGL    845  30.37  27.82
1     WMT     65  14.26   4.61
2    MSFT     64  30.97   2.12
----------------------------------------------------------------
        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2017           35          7  Sunny
2  3/1/2017           28          2   Snow
3  4/1/2017           32          7   Rain
4  1/1/2017           31          4  Sunny

# Create Excel File

If have a No Module error(openpyxl). Then run Command in CMD

pip install openpyxl

In [8]:
with pd.ExcelWriter('stocks_wheather.xlsx') as writer:
    df_stocks.to_excel(writer, sheet_name="stocks")
    weather_data.to_excel(writer, sheet_name="weather")

print('File Created Successfully!...')

File Created Successfully!...

# Read CSV File

In [9]:
df = pd.read_csv("weather_data.csv")

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2017           35          7  Sunny
2  3/1/2017           28          2   Snow
3  4/1/2017           32          7   Rain
4  1/1/2017           31          4  Sunny

# Read Excel(xlsx) File

In [12]:
df = pd.read_excel("stocks_wheather.xlsx", "weather")

df

   Unnamed: 0       day  temperature  windspeed  event
0           0  1/1/2017           32          6   Rain
1           1  2/1/2017           35          7  Sunny
2           2  3/1/2017           28          2   Snow
3           3  4/1/2017           32          7   Rain
4           4  1/1/2017           31          4  Sunny