# DataFrame
-----------

DataFrame is most commonly used object in pandas. It is a table like datastructure containing row and columns similar to excel spredsheet.

In [1]:
# Define the Data

weather_data = {
    'day': ['1/1/2017', '2/1/2017', '3/1/2017', '4/1/2017', '1/1/2017'],
    'temperature':[32, 35, 28, 32, 31],
    'windspeed': [6, 7, 2, 7, 4],
    'event': ['Rain', 'Sunny', 'Snow', 'Rain', 'Sunny']
}

print(weather_data, type(weather_data))

{'day': ['1/1/2017', '2/1/2017', '3/1/2017', '4/1/2017', '1/1/2017'], 'temperature': [32, 35, 28, 32, 31], 'windspeed': [6, 7, 2, 7, 4], 'event': ['Rain', 'Sunny', 'Snow', 'Rain', 'Sunny']} <class 'dict'>

In [2]:
# Create DataFrame

import pandas as pd

df = pd.DataFrame(weather_data)

df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2017           35          7  Sunny
2  3/1/2017           28          2   Snow
3  4/1/2017           32          7   Rain
4  1/1/2017           31          4  Sunny

# Create Csv File Using DataFrame Values

In [3]:
df.to_csv('weather_data.csv', index=False)

print('File Created Successfully!...')

File Created Successfully!...

# Read CSV File

In [4]:
readFile = pd.read_csv('weather_data.csv')

readFile

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2017           35          7  Sunny
2  3/1/2017           28          2   Snow
3  4/1/2017           32          7   Rain
4  1/1/2017           31          4  Sunny

In [5]:
# to find Shape

df.shape

(5, 4)