# Different ways of Creating DataFrame

# 1 Using Dictionary

In [1]:
import pandas as pd

In [2]:
# Define the Data

weather_data = {
    'day': ['1/1/2017', '2/1/2017', '3/1/2017', '4/1/2017', '1/1/2017'],
    'temperature':[32, 35, 28, 32, 31],
    'windspeed': [6, 7, 2, 7, 4],
    'event': ['Rain', 'Sunny', 'Snow', 'Rain', 'Sunny']
}

print(weather_data, type(weather_data))

{'day': ['1/1/2017', '2/1/2017', '3/1/2017', '4/1/2017', '1/1/2017'], 'temperature': [32, 35, 28, 32, 31], 'windspeed': [6, 7, 2, 7, 4], 'event': ['Rain', 'Sunny', 'Snow', 'Rain', 'Sunny']} <class 'dict'>

In [3]:
# Create DataFrame

df01 = pd.DataFrame(weather_data)

df01

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2017           35          7  Sunny
2  3/1/2017           28          2   Snow
3  4/1/2017           32          7   Rain
4  1/1/2017           31          4  Sunny

# 2. Using Tuples & List

In [4]:
# Define The Data

weather_data = [
    ('1/1/2017', 32, 6, 'Rain'),
    ('2/1/2027', 31, 9, 'Sunny'),
    ('1/3/2017', 30, 2, 'Snow')
]

print(weather_data, type(weather_data))

[('1/1/2017', 32, 6, 'Rain'), ('2/1/2027', 31, 9, 'Sunny'), ('1/3/2017', 30, 2, 'Snow')] <class 'list'>

In [6]:
# Create DataFrame

df02 = pd.DataFrame(data=weather_data, columns=['day', 'temperature', 'windspeed', 'event'])

df02

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2027           31          9  Sunny
2  1/3/2017           30          2   Snow

# Using List of Dictionary

In [8]:
# Define The Data

weather_data = [
    {'day': '1/1/2017', 'temperature': 32,'windspeed': 6, 'event': 'Rain'},
    {'day':'2/1/2027', 'temperature': 31,'windspeed': 9, 'event': 'Sunny'},
    {'day':'1/3/2017', 'temperature': 30,'windspeed': 2, 'event': 'Snow'}
]

print(weather_data, type(weather_data))

[{'day': '1/1/2017', 'temperature': 32, 'windspeed': 6, 'event': 'Rain'}, {'day': '2/1/2027', 'temperature': 31, 'windspeed': 9, 'event': 'Sunny'}, {'day': '1/3/2017', 'temperature': 30, 'windspeed': 2, 'event': 'Snow'}] <class 'list'>

In [9]:
# Create DataFrame

df03 = pd.DataFrame(data=weather_data, columns=['day', 'temperature', 'windspeed', 'event'])

df03

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  2/1/2027           31          9  Sunny
2  1/3/2017           30          2   Snow