# Using mysql-connector-python + Pandas

In [1]:
import mysql.connector
import pandas as pd

# Connect to MySQL
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="company"
)

# Query
query = "SELECT * FROM employees"

# Load into DataFrame
df = pd.read_sql(query, conn)

# Show data
print(df)

# Close connection
conn.close()

   id   name  salary
0   2    Dev   60000
1   5  Selva   70000

C:\Users\Dell 7490\AppData\Local\Temp\ipykernel_16876\1217610679.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

# Using SQLAlchemy

More scalable & widely used in real projects

# Install

pip install sqlalchemy pymysql

In [2]:
import pandas as pd
from sqlalchemy import create_engine

# Create connection engine
# create_engine("mysql+pymysql://user_name:your_password@localhost/your_database")
engine = create_engine("mysql+pymysql://root:@localhost/company")

# Query
query = "SELECT * FROM employees"

# Load into DataFrame
df = pd.read_sql(query, engine)

df

   id   name  salary
0   2    Dev   60000
1   5  Selva   70000

In [6]:
df = pd.read_sql("SELECT name FROM employees", engine)

df

    name
0    Dev
1  Selva