Pivot basics
------------

Reshape data (produce a “pivot” table) based on column values. Uses unique values from specified index / columns to form axes of the resulting DataFrame.

In [2]:
import pandas as pd

import numpy as np

In [4]:
df = pd.read_csv("weather.csv")

df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [5]:
df.pivot(index='city',columns='date')

         temperature                   humidity
date        5/1/2017 5/2/2017 5/3/2017 5/1/2017 5/2/2017 5/3/2017
city
beijing           80       77       79       26       30       35
mumbai            75       78       82       80       83       85
new york          65       66       68       56       58       60

In [6]:
df.pivot(index='city',columns='date',values="humidity")

date      5/1/2017  5/2/2017  5/3/2017
city
beijing         26        30        35
mumbai          80        83        85
new york        56        58        60

In [5]:
df.pivot(index='date',columns='city')

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [7]:
df.pivot(index='humidity',columns='city')

              date                     temperature
city       beijing    mumbai  new york     beijing mumbai new york
humidity
26        5/1/2017       NaN       NaN        80.0    NaN      NaN
30        5/2/2017       NaN       NaN        77.0    NaN      NaN
35        5/3/2017       NaN       NaN        79.0    NaN      NaN
56             NaN       NaN  5/1/2017         NaN    NaN     65.0
58             NaN       NaN  5/2/2017         NaN    NaN     66.0
60             NaN       NaN  5/3/2017         NaN    NaN     68.0
80             NaN  5/1/2017       NaN         NaN   75.0      NaN
83             NaN  5/2/2017       NaN         NaN   78.0      NaN
85             NaN  5/3/2017       NaN         NaN   82.0      NaN

Pivot Table
-----------

Create a spreadsheet-style pivot table as a DataFrame. The levels in the pivot table will be stored in MultiIndex objects (hierarchical indexes)

In [16]:
df = pd.read_csv("weather2.csv")

df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26
8  5/3/2017    mumbai           85        30
9  5/3/2017    mumbai           82        32

In [17]:
#  pandas will calculate the mean for each group of values for each column (by default for pivot_table).
'''
For the humidity column:
For mumbai:

On 5/1/2017: The humidity values are 80 and 83. The average is (80 + 83) / 2 = 81.5.
On 5/2/2017: The humidity values are 85 and 26. The average is (85 + 26) / 2 = 55.5.
For new york:

On 5/1/2017: The humidity values are 56 and 54. The average is (56 + 54) / 2 = 55.0.
On 5/2/2017: The humidity values are 60 and 62. The average is (60 + 62) / 2 = 61.0.
For the temperature column:
For mumbai:

On 5/1/2017: The temperature values are 75 and 78. The average is (75 + 78) / 2 = 76.5.
On 5/2/2017: The temperature values are 82 and 80. The average is (82 + 80) / 2 = 81.0.
For new york:

On 5/1/2017: The temperature values are 65 and 61. The average is (65 + 61) / 2 = 63.0.
On 5/2/2017: The temperature values are 70 and 72. The average is (70 + 72) / 2 = 71.0.
'''

df.pivot_table(index="city",columns="date")

         humidity                   temperature
date     5/1/2017 5/2/2017 5/3/2017    5/1/2017 5/2/2017 5/3/2017
city
mumbai       81.5     55.5     31.0        76.5     81.0     83.5
new york     55.0     61.0      NaN        63.0     71.0      NaN

Margins
-------

In [20]:
df.pivot_table(index="city",columns="date", margins=True,aggfunc=np.sum)

C:\Users\Dell 7490\AppData\Local\Temp\ipykernel_21964\2241513779.py:1: FutureWarning: The provided callable <function sum at 0x000001A84D256840> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index="city",columns="date", margins=True,aggfunc=np.sum)
C:\Users\Dell 7490\AppData\Local\Temp\ipykernel_21964\2241513779.py:1: FutureWarning: The provided callable <function sum at 0x000001A84D256840> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index="city",columns="date", margins=True,aggfunc=np.sum)
C:\Users\Dell 7490\AppData\Local\Temp\ipykernel_21964\2241513779.py:1: FutureWarning: The provided callable <function sum at 0x000001A84D256840> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df.pivot_table(index="city",columns="date", margins=True,aggfunc=np.sum)

         humidity                        temperature
date     5/1/2017 5/2/2017 5/3/2017  All    5/1/2017 5/2/2017 5/3/2017  All
city
mumbai      163.0    111.0     62.0  336       153.0    162.0    167.0  482
new york    110.0    122.0      NaN  232       126.0    142.0      NaN  268
All         273.0    233.0     62.0  568       279.0    304.0    167.0  750

Grouper
-------
Use pd.Grouper with the frequency set to Month End (ME) to group the data by the last day of each month.

The values in the table are the average of the temperature and humidity for each city, grouped by the month-end date.

1. 2017-05-31, the mean humidity is (56 + 54 + 60) / 3 = 56.67, 
2. the mean temperature is (65 + 61 + 70) / 3 = 65.33.
3. 2017-12-31, the mean humidity is (50 + 52 + 51) / 3 = 51.00, 
4. the mean temperature is (30 + 28 + 25) / 3 = 27.67.

In [21]:
df = pd.read_csv("weather3.csv")

df

        date      city  temperature  humidity
0   5/1/2017  new york           65        56
1   5/2/2017  new york           61        54
2   5/3/2017  new york           70        60
3  12/1/2017  new york           30        50
4  12/2/2017  new york           28        52
5  12/3/2017  new york           25        51

In [22]:
df['date'] = pd.to_datetime(df['date'])

In [23]:
df.pivot_table(index=pd.Grouper(freq='ME',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667

# ToDay Task

1. To Remove the Index Values

2. To Find the Column Names

3. To Find the Column & Row Count

4. To Find All Column Details For Customer Id - 1Ef7b82A4CAAD10

5. To Find the All Column Details For First Name - Start with S

6. Use Groub By for Follwing Three Columns - 1. Company, 2. City, 3. Country

7. To Find the Column values For - Email (UserName : zunigavanessa@smith.info --> zunigavanessa)

8. To Use Pivot For df.pivot(index='Subscription Date',columns='Company')

In [5]:
import pandas as pd

In [6]:
# Load CSV
df = pd.read_csv("sales.csv")

df

         Date Region Product  Sales
0  2024-01-01  North  Laptop  50000
1  2024-01-01  South  Laptop  45000
2  2024-01-01  North  Mobile  20000
3  2024-01-02  South  Mobile  22000
4  2024-01-02  North  Laptop  55000
5  2024-01-02  South  Laptop  47000
6  2024-01-03  North  Mobile  25000
7  2024-01-03  South  Mobile  27000

In [16]:
df = df.drop_duplicates(subset=["Date", "Product"])

pivot_df = df.pivot(index="Date", columns="Product")

pivot_df

           Region           Sales
Product    Laptop Mobile   Laptop   Mobile
Date
2024-01-01  North  North  50000.0  20000.0
2024-01-02  North  South  55000.0  22000.0
2024-01-03    NaN  North      NaN  25000.0

In [17]:
pivot_df = df.pivot(index="Date", columns="Product", values="Sales")

pivot_df

Product      Laptop   Mobile
Date
2024-01-01  50000.0  20000.0
2024-01-02  55000.0  22000.0
2024-01-03      NaN  25000.0